name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt || true

      - name: Ruff (format check)
        run: |
          ruff format --check .

      - name: Ruff (lint)
        run: |
          ruff check . --output-format=github

      - name: Type check (mypy)
        run: |
          mypy --strict data_server

      - name: Unit tests
        run: |
          coverage run -m unittest discover -v -s tests/unit

      - name: Integration tests
        run: |
          python -m unittest discover -v -s tests/int

      - name: Coverage report
        run: |
          coverage report -m
